//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKütüphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMANET
    {
        public int EMANET_ID { get; set; }
        public Nullable<int> KITAP { get; set; }
        public Nullable<int> UYE { get; set; }
        public Nullable<int> PERSONEL { get; set; }
        public Nullable<System.DateTime> EMANET_TARIHI { get; set; }
        public Nullable<System.DateTime> TESLIM_TARIHI { get; set; }
        public Nullable<bool> ISLEMDURUM { get; set; }
        public Nullable<System.DateTime> UYE_TESLIM_TARIHI { get; set; }
    
        public virtual KITAPLAR KITAPLAR { get; set; }
        public virtual UYELER UYELER { get; set; }
        public virtual PERSONEL PERSONEL1 { get; set; }
    }
}
