//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKütüphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILETISIM
    {
        public int ILETISIM_ID { get; set; }
        public string ILETISIM_AD { get; set; }
        public string ILETISIM_EMAİL { get; set; }
        public string ILETISIM_TELEFON { get; set; }
        public string ILETISIM_MESAJ { get; set; }
    }
}
