//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKütüphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KITAPLAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KITAPLAR()
        {
            this.EMANET = new HashSet<EMANET>();
        }
    
        public int KITAP_ID { get; set; }
        public string KITAP_ADI { get; set; }
        public Nullable<int> KATEGORI { get; set; }
        public Nullable<int> YAZAR { get; set; }
        public Nullable<int> S_SAYISI { get; set; }
        public string YAYINEVI { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public string KITAPFOTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMANET> EMANET { get; set; }
        public virtual KATEGORI KATEGORI1 { get; set; }
        public virtual YAZARLAR YAZARLAR { get; set; }
    }
}
