//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKütüphane.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KÜTÜPHANE_YONETİM_SİSTEMİEntities : DbContext
    {
        public KÜTÜPHANE_YONETİM_SİSTEMİEntities()
            : base("name=KÜTÜPHANE_YONETİM_SİSTEMİEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EMANET> EMANET { get; set; }
        public virtual DbSet<KATEGORI> KATEGORI { get; set; }
        public virtual DbSet<KITAPLAR> KITAPLAR { get; set; }
        public virtual DbSet<PERSONEL> PERSONEL { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UYELER> UYELER { get; set; }
        public virtual DbSet<YAZARLAR> YAZARLAR { get; set; }
        public virtual DbSet<ILETISIM> ILETISIM { get; set; }
    }
}
