//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKütüphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UYELER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UYELER()
        {
            this.EMANET = new HashSet<EMANET>();
        }
    
        public int UYE_ID { get; set; }
        public string UYE_AD { get; set; }
        public string UYE_SOYAD { get; set; }
        public string E_POSTA { get; set; }
        public string TELEFON { get; set; }
        public string KULLANICIADI { get; set; }
        public string SİFRE { get; set; }
        public string OKUL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMANET> EMANET { get; set; }
    }
}
